name: document_vault
description: A beautiful offline document vault
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Storage
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # File Handling
  file_picker: ^8.1.2
  image_picker: ^1.0.7
  pdfx: ^2.6.0
  
  # UI & Utilities
  flutter_staggered_animations: ^1.1.1
  intl: ^0.18.0
  uuid: ^4.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.1
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/